# Generated by Django 5.1.2 on 2024-10-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('is_owner', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('DeliveryPartner', 'DeliveryPartner'), ('RestaurantOwner', 'RestaurantOwner'), ('RestaurantEmployee', 'RestaurantEmployee'), ('FranchiseOwner', 'FranchiseOwner'), ('FranchiseEmployee', 'FranchiseEmployee'), ('Admin', 'Admin'), ('AdminEmployee', 'AdminEmploy')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
